-- Seed data — local + staging only. Production seeds are forbidden (docs/03-environments.md).

-- Models
-- 主 provider：火山方舟豆包 Seedream（ADR-017）。provider_model 填方舟控制台的
-- Model ID（或 Endpoint ID）——开通模型服务后如有出入直接改这行即可，无需改代码。
-- config.watermark：false 关闭右下角"AI生成"水印（合规要求变化时改回 true）。
insert into public.models (id, display_name, type, provider, provider_model, credits_cost, config, sort_order)
values
  ('doubao-seedream-5-lite', 'Doubao Seedream 5.0 Lite', 'text_to_image', 'seedream', 'doubao-seedream-5-0-lite-260128', 1,
   '{"watermark": true}', 0),
  ('fal-flux-schnell', 'FLUX schnell（备选）', 'text_to_image', 'fal', 'fal-ai/flux/schnell', 1,
   '{"default_width":1024,"default_height":1024}', 10)
on conflict (id) do nothing;

-- Templates：由 scripts/generate-template-assets.mjs 生成与维护（目录在 scripts/template-catalog.mjs）。
-- 推荐尺寸对齐 Seedream 2K 档（像素模式总像素下限 2560x1440）。

-- BEGIN generated templates (scripts/generate-template-assets.mjs — 手改会被覆盖)
insert into public.templates
  (slug, title, theme, reference_image_path, sample_output_paths, base_prompt, negative_prompt,
   model_id, recommended_width, recommended_height, credits_cost, keyword_placeholder, sort_order)
values
  ('game-hero', '史诗奇幻骑士', 'game_character', 'game-hero.jpg', array['game-hero-sample.jpg'],
   'concept art of {subject}, heroic fantasy game character, dramatic rim lighting, highly detailed, artstation trending',
   'blurry, low quality, watermark, text, deformed',
   'doubao-seedream-5-lite', 1728, 2304, 1, '例如：手持长剑的女骑士', 0),
  ('game-cyberpunk', '赛博朋克角色', 'game_character', 'game-cyberpunk.jpg', array['game-cyberpunk-sample.jpg'],
   'character concept art of {subject}, cyberpunk style, neon-lit rainy city backdrop, holographic UI elements, chrome and leather outfit, cinematic lighting, ultra detailed',
   'blurry, low quality, watermark, text, deformed',
   'doubao-seedream-5-lite', 1728, 2304, 1, '例如：机械义肢的女黑客', 1),
  ('game-xianxia', '国风仙侠立绘', 'game_character', 'game-xianxia.jpg', array['game-xianxia-sample.jpg'],
   'full body game character illustration of {subject}, Chinese xianxia fantasy style, flowing silk robes, ethereal clouds and mountain mist, elegant ink-wash color palette, intricate details',
   'blurry, low quality, watermark, text, deformed',
   'doubao-seedream-5-lite', 1728, 2304, 1, '例如：御剑的白衣剑仙', 2),
  ('game-pixel', '像素风角色', 'game_character', 'game-pixel.jpg', array['game-pixel-sample.jpg'],
   'pixel art game sprite of {subject}, 32-bit retro RPG style, vibrant colors, idle pose, clean pixel work, dark dungeon background',
   'blurry, low quality, watermark, text, deformed',
   'doubao-seedream-5-lite', 1728, 2304, 1, '例如：举盾的小骑士', 3),
  ('game-anime', '二次元立绘', 'game_character', 'game-anime.jpg', array['game-anime-sample.jpg'],
   'anime game character full-body illustration of {subject}, cel shading, vivid colors, dynamic pose, clean lineart, white gradient background, gacha game splash art style',
   'blurry, low quality, watermark, text, deformed',
   'doubao-seedream-5-lite', 1728, 2304, 1, '例如：双马尾魔法少女', 4),
  ('game-mecha', '机甲驾驶员', 'game_character', 'game-mecha.jpg', array['game-mecha-sample.jpg'],
   'concept art of {subject} as a mecha pilot with giant robot armor, sci-fi hangar background, glowing energy core, hard surface design, dramatic low angle',
   'blurry, low quality, watermark, text, deformed',
   'doubao-seedream-5-lite', 1728, 2304, 1, '例如：短发机甲女飞行员', 5),
  ('game-wasteland', '废土幸存者', 'game_character', 'game-wasteland.jpg', array['game-wasteland-sample.jpg'],
   'post-apocalyptic game character concept of {subject}, wasteland survivor gear, gas mask details, rusted metal and worn leather, sandstorm atmosphere, gritty realistic style',
   'blurry, low quality, watermark, text, deformed',
   'doubao-seedream-5-lite', 1728, 2304, 1, '例如：背狙击枪的独行者', 6),
  ('game-gothic', '哥特暗黑风', 'game_character', 'game-gothic.jpg', array['game-gothic-sample.jpg'],
   'dark gothic game character art of {subject}, victorian gothic attire, pale moonlight, ornate silver accessories, bats and fog, dark souls inspired atmosphere',
   'blurry, low quality, watermark, text, deformed',
   'doubao-seedream-5-lite', 1728, 2304, 1, '例如：执银杖的吸血鬼伯爵', 7),
  ('game-norse', '北欧神话战士', 'game_character', 'game-norse.jpg', array['game-norse-sample.jpg'],
   'norse mythology game character concept of {subject}, viking runes glowing, fur and bronze armor, snowstorm fjord backdrop, epic god-like presence',
   'blurry, low quality, watermark, text, deformed',
   'doubao-seedream-5-lite', 1728, 2304, 1, '例如：双手战锤的狂战士', 8),
  ('game-wuxia', '武侠水墨', 'game_character', 'game-wuxia.jpg', array['game-wuxia-sample.jpg'],
   'wuxia martial artist {subject}, Chinese ink painting style game art, dynamic sword stance, splashing ink strokes, minimal color accent, rice paper texture',
   'blurry, low quality, watermark, text, deformed',
   'doubao-seedream-5-lite', 1728, 2304, 1, '例如：竹林中的盲剑客', 9),
  ('game-magic-academy', '魔法学院学生', 'game_character', 'game-magic-academy.jpg', array['game-magic-academy-sample.jpg'],
   'game character design of {subject} as a magic academy student, wizard robe with house emblem, floating spellbook and glowing runes, warm library background, painterly style',
   'blurry, low quality, watermark, text, deformed',
   'doubao-seedream-5-lite', 1728, 2304, 1, '例如：抱猫的天才学妹', 10),
  ('game-steampunk', '蒸汽朋克发明家', 'game_character', 'game-steampunk.jpg', array['game-steampunk-sample.jpg'],
   'steampunk game character concept of {subject}, brass goggles and clockwork gadgets, steam pipes background, victorian workshop, warm copper tones',
   'blurry, low quality, watermark, text, deformed',
   'doubao-seedream-5-lite', 1728, 2304, 1, '例如：机械臂的天才少女', 11),
  ('game-space-opera', '星际指挥官', 'game_character', 'game-space-opera.jpg', array['game-space-opera-sample.jpg'],
   'space opera game character of {subject}, sleek sci-fi commander uniform, starship bridge backdrop, holographic star map, cinematic blue lighting',
   'blurry, low quality, watermark, text, deformed',
   'doubao-seedream-5-lite', 1728, 2304, 1, '例如：白制服的舰队司令', 12),
  ('game-chibi', 'Q版游戏角色', 'game_character', 'game-chibi.jpg', array['game-chibi-sample.jpg'],
   'chibi game character of {subject}, super deformed proportions, big sparkling eyes, casual RPG outfit, cheerful colors, mobile game style',
   'blurry, low quality, watermark, text, deformed',
   'doubao-seedream-5-lite', 1728, 2304, 1, '例如：背大剑的小勇者', 13),
  ('game-monster', '怪物图鉴', 'game_character', 'game-monster.jpg', array['game-monster-sample.jpg'],
   'fantasy creature design of {subject}, monster manual illustration style, detailed anatomy, scales and claws, neutral parchment background, professional game bestiary art',
   'blurry, low quality, watermark, text, deformed',
   'doubao-seedream-5-lite', 1728, 2304, 1, '例如：双头岩浆龙', 14),
  ('game-cthulhu', '克苏鲁调查员', 'game_character', 'game-cthulhu.jpg', array['game-cthulhu-sample.jpg'],
   'cosmic horror game character of {subject}, 1920s investigator attire, eldritch tentacle shadows, sickly green fog, lovecraftian atmosphere, dramatic chiaroscuro',
   'blurry, low quality, watermark, text, deformed',
   'doubao-seedream-5-lite', 1728, 2304, 1, '例如：提油灯的老侦探', 15),
  ('blind-box', '经典奶油盲盒', 'blind_box', 'blind-box.jpg', array['blind-box-sample.jpg'],
   'cute chibi blind box figure of {subject}, soft pastel colors, studio product photo, 3d render, clean background',
   'blurry, low quality, watermark, text, deformed',
   'doubao-seedream-5-lite', 2048, 2048, 1, '例如：戴帽子的柴犬', 16),
  ('bb-macaron', '马卡龙糖果系', 'blind_box', 'bb-macaron.jpg', array['bb-macaron-sample.jpg'],
   'cute chibi blind box figure of {subject}, macaron candy color palette, glossy smooth surface, dessert accessories, pastel pink studio background, 3d render',
   'blurry, low quality, watermark, text, deformed',
   'doubao-seedream-5-lite', 2048, 2048, 1, '例如：抱草莓的小熊', 17),
  ('bb-plush', '毛绒材质', 'blind_box', 'bb-plush.jpg', array['bb-plush-sample.jpg'],
   'blind box figure of {subject} in fluffy plush texture, soft fuzzy material, kawaii expression, cozy warm lighting, clean studio shot, 3d render',
   'blurry, low quality, watermark, text, deformed',
   'doubao-seedream-5-lite', 2048, 2048, 1, '例如：围围巾的企鹅', 18),
  ('bb-jelly', '果冻半透明', 'blind_box', 'bb-jelly.jpg', array['bb-jelly-sample.jpg'],
   'translucent jelly material blind box figure of {subject}, gummy candy texture, light passing through, glossy highlights, mint background, 3d render',
   'blurry, low quality, watermark, text, deformed',
   'doubao-seedream-5-lite', 2048, 2048, 1, '例如：果冻小恐龙', 19),
  ('bb-guochao', '国潮风', 'blind_box', 'bb-guochao.jpg', array['bb-guochao-sample.jpg'],
   'chinese guochao style blind box figure of {subject}, traditional opera costume elements, auspicious cloud patterns, red and gold palette, festive studio shot, 3d render',
   'blurry, low quality, watermark, text, deformed',
   'doubao-seedream-5-lite', 2048, 2048, 1, '例如：舞狮的小老虎', 20),
  ('bb-zodiac', '星空主题', 'blind_box', 'bb-zodiac.jpg', array['bb-zodiac-sample.jpg'],
   'celestial zodiac themed blind box figure of {subject}, starry translucent cape, tiny constellation crown, deep blue and gold, dreamy glow, 3d render',
   'blurry, low quality, watermark, text, deformed',
   'doubao-seedream-5-lite', 2048, 2048, 1, '例如：摘星星的小鹿', 21),
  ('bb-food', '美食拟人', 'blind_box', 'bb-food.jpg', array['bb-food-sample.jpg'],
   'food-themed blind box figure of {subject} dressed as a dessert chef, wearing food hat, miniature kitchen props, cream tones, 3d render',
   'blurry, low quality, watermark, text, deformed',
   'doubao-seedream-5-lite', 2048, 2048, 1, '例如：戴厨师帽的仓鼠', 22),
  ('bb-christmas', '圣诞限定', 'blind_box', 'bb-christmas.jpg', array['bb-christmas-sample.jpg'],
   'christmas edition blind box figure of {subject}, santa hat and scarf, tiny gift box, snow dusted base, warm fairy lights bokeh, 3d render',
   'blurry, low quality, watermark, text, deformed',
   'doubao-seedream-5-lite', 2048, 2048, 1, '例如：抱礼物的北极熊', 23),
  ('bb-sakura', '樱花和风', 'blind_box', 'bb-sakura.jpg', array['bb-sakura-sample.jpg'],
   'japanese sakura themed blind box figure of {subject}, kimono with cherry blossom pattern, falling petals, soft pink gradient background, 3d render',
   'blurry, low quality, watermark, text, deformed',
   'doubao-seedream-5-lite', 2048, 2048, 1, '例如：穿和服的小猫', 24),
  ('bb-ocean', '海洋生物', 'blind_box', 'bb-ocean.jpg', array['bb-ocean-sample.jpg'],
   'ocean themed blind box figure of {subject}, wearing cute diving helmet, bubbles and coral base, aqua blue palette, 3d render',
   'blurry, low quality, watermark, text, deformed',
   'doubao-seedream-5-lite', 2048, 2048, 1, '例如：戴潜水盔的海獭', 25),
  ('bb-retro-toy', '复古铁皮玩具', 'blind_box', 'bb-retro-toy.jpg', array['bb-retro-toy-sample.jpg'],
   'retro tin toy style blind box figure of {subject}, vintage wind-up key on back, slightly worn paint texture, nostalgic warm tones, 3d render',
   'blurry, low quality, watermark, text, deformed',
   'doubao-seedream-5-lite', 2048, 2048, 1, '例如：发条小机器人', 26),
  ('bb-astronaut', '太空宇航员', 'blind_box', 'bb-astronaut.jpg', array['bb-astronaut-sample.jpg'],
   'astronaut blind box figure of {subject}, tiny spacesuit with clear helmet, moon surface base, star field backdrop, 3d render',
   'blurry, low quality, watermark, text, deformed',
   'doubao-seedream-5-lite', 2048, 2048, 1, '例如：登月的小仓鼠', 27),
  ('bb-forest', '森林精灵', 'blind_box', 'bb-forest.jpg', array['bb-forest-sample.jpg'],
   'forest spirit blind box figure of {subject}, leaf cloak and acorn hat, mushroom base with fireflies, mori kei palette, 3d render',
   'blurry, low quality, watermark, text, deformed',
   'doubao-seedream-5-lite', 2048, 2048, 1, '例如：戴橡果帽的刺猬', 28),
  ('bb-crystal', '水晶质感', 'blind_box', 'bb-crystal.jpg', array['bb-crystal-sample.jpg'],
   'crystal gemstone blind box figure of {subject}, faceted translucent body, prismatic light refraction, elegant dark backdrop, 3d render',
   'blurry, low quality, watermark, text, deformed',
   'doubao-seedream-5-lite', 2048, 2048, 1, '例如：水晶独角兽', 29),
  ('bb-mecha-cute', '机甲萌宠', 'blind_box', 'bb-mecha-cute.jpg', array['bb-mecha-cute-sample.jpg'],
   'cute mecha armor blind box figure of {subject}, pastel robot suit pieces, tiny LED details, clean white tech background, 3d render',
   'blurry, low quality, watermark, text, deformed',
   'doubao-seedream-5-lite', 2048, 2048, 1, '例如：穿机甲的橘猫', 30),
  ('bb-bread', '烘焙小队', 'blind_box', 'bb-bread.jpg', array['bb-bread-sample.jpg'],
   'freshly baked bread themed blind box figure of {subject}, golden crust texture body, flour dust, bakery wooden board base, cozy morning light, 3d render',
   'blurry, low quality, watermark, text, deformed',
   'doubao-seedream-5-lite', 2048, 2048, 1, '例如：牛角包小猫', 31)
on conflict (slug) do update set
  title = excluded.title, theme = excluded.theme,
  reference_image_path = excluded.reference_image_path,
  sample_output_paths = excluded.sample_output_paths,
  base_prompt = excluded.base_prompt, negative_prompt = excluded.negative_prompt,
  model_id = excluded.model_id, recommended_width = excluded.recommended_width,
  recommended_height = excluded.recommended_height, credits_cost = excluded.credits_cost,
  keyword_placeholder = excluded.keyword_placeholder, sort_order = excluded.sort_order;
-- END generated templates
