onlyBuiltDependencies:
  - esbuild
  - sharp
  - unrs-resolver
ignoredBuiltDependencies:
  - msw
  - protobufjs
allowBuilds:
  esbuild: true
  msw: true
  protobufjs: false
  sharp: true
  unrs-resolver: true
