onlyBuiltDependencies:
  - esbuild
  - sharp
  - unrs-resolver
ignoredBuiltDependencies:
  - msw
  - protobufjs
  - '@sentry/cli'
allowBuilds:
  '@sentry/cli': false
  esbuild: true
  msw: true
  protobufjs: false
  sharp: true
  unrs-resolver: true
